# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hubblesite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://dockerdemotesting.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fd80cf34eb0940cf97287556fc6bfc1b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ec810826992c469a98025963627f0658 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: dockerdemotesting.azurecr.io/hubblesite-api-img:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hubblesite'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3ef111afb52f43e6865755944dd7d062 }}
        images: 'dockerdemotesting.azurecr.io/hubblesite-api-img:${{ github.sha }}'
